#!/usr/bin/env bash
# Generate references/env.local.sh for BOTH skills from the currently-resolved
# toolchain, so a bootstrapped environment (conda binaries on /proj, a torch venv,
# a non-standard ORFS) is auto-discovered on the next session with no manual edit.
#
# Layer 4 of the bootstrap (detect → plan → install → PIN → verify).
# See docs/superpowers/plans/r2g-skills-bootstrap-2026-07-08.md.
#
# It sources scripts/flow/_env.sh to resolve every path, then writes only the
# lines that autodetect would otherwise miss:
#   - ORFS_ROOT (pinned always — makes discovery deterministic)
#   - openroad/yosys/sta ONLY when they are NOT under $ORFS_ROOT/tools/install
#     (i.e. they came from conda/PATH, which a fresh shell might not find)
#   - the conda-env signoff tools (iverilog/vvp/verilator/klayout/magic/netgen)
#   - PDK_ROOT (+ derived SKY130A_DIR)
#   - R2G_GRAPH_PYTHON (the torch venv for the graph stage)
# Every existing env.local.sh is backed up once before it is replaced.
set -uo pipefail

SETUP_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
FLOW_DIR_SH="$(cd -- "$SETUP_DIR/../flow" && pwd)"        # sibling _env.sh (byte-identical copy)
SKILL_ROOT="$(cd -- "$SETUP_DIR/../.." && pwd)"           # …/r2g-skills/eda-install
SKILLS_ROOT="$(cd -- "$SKILL_ROOT/.." && pwd)"            # …/r2g-skills (targets are sibling skills)

graph_python="${R2G_GRAPH_PYTHON:-}"
do_dry=0
declare -a TARGETS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --graph-python) graph_python="${2:-}"; shift 2 ;;
    --dry-run)      do_dry=1; shift ;;
    --target)       TARGETS+=("${2:-}"); shift 2 ;;   # override output dir(s), repeatable
    -h|--help)
      echo "usage: write_env_local.sh [--graph-python PATH] [--dry-run] [--target references-dir]..."; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

# Resolve the toolchain (this also sources any existing env.local.sh — regenerating
# from resolved values is idempotent). Chatter to stderr; keep our stdout clean.
export R2G_GRAPH_PYTHON="$graph_python"
# shellcheck source=/dev/null
source "$FLOW_DIR_SH/_env.sh" 1>&2

# Default targets: every consumer skill's references/ dir (rtl-acquire delegates
# to the same shared _env.sh + pins, incl. R2G_GRAPH_PYTHON for netlist graphs).
if [[ "${#TARGETS[@]}" -eq 0 ]]; then
  TARGETS=(
    "$SKILLS_ROOT/signoff-loop/references"
    "$SKILLS_ROOT/def-graph/references"
    "$SKILLS_ROOT/rtl-acquire/references"
  )
fi

_orfs_install_prefix="${ORFS_ROOT:-}/tools/install/"

# emit_export VAR VALUE [skip_if_under_prefix]
emit_export() {
  local var="$1" val="$2" skip_prefix="${3:-}"
  [[ -z "$val" ]] && return 0
  if [[ -n "$skip_prefix" && "$val" == "$skip_prefix"* ]]; then
    return 0   # under ORFS tools/install → _env.sh already finds it, don't pin
  fi
  printf 'export %s="%s"\n' "$var" "$val"
}

build_content() {
  cat <<'HDR'
# Local environment overrides for the r2g-skills toolchain.
#
# GENERATED by scripts/setup/write_env_local.sh (bootstrap pin step). Pins tool
# discovery in scripts/flow/_env.sh to the paths resolved on this machine so a
# no-sudo / conda / /proj-staged toolchain is found with no manual edit.
# Regenerate:  bash <skill>/scripts/setup/write_env_local.sh
# Every value is optional; delete a line to fall back to autodetection.
HDR
  echo
  echo "# --- OpenROAD-flow-scripts checkout --------------------------------------"
  emit_export ORFS_ROOT "${ORFS_ROOT:-}"
  echo
  echo "# --- Tool binaries (pinned only when outside \$ORFS_ROOT/tools/install) ----"
  emit_export OPENROAD_EXE  "${OPENROAD_EXE:-}"  "$_orfs_install_prefix"
  emit_export YOSYS_EXE     "${YOSYS_EXE:-}"     "$_orfs_install_prefix"
  emit_export STA_EXE       "${STA_EXE:-}"       "$_orfs_install_prefix"
  emit_export IVERILOG_EXE  "${IVERILOG_EXE:-}"
  emit_export VVP_EXE       "${VVP_EXE:-}"
  emit_export VERILATOR_EXE "${VERILATOR_EXE:-}"
  emit_export KLAYOUT_CMD   "${KLAYOUT_CMD:-}"
  emit_export MAGIC_EXE     "${MAGIC_EXE:-}"
  emit_export NETGEN_EXE    "${NETGEN_EXE:-}"
  echo
  echo "# --- PDK root (sky130 DRC/LVS with Magic / Netgen) -----------------------"
  if [[ -n "${PDK_ROOT:-}" ]]; then
    printf 'export PDK_ROOT="%s"\n' "$PDK_ROOT"
    printf '[ -d "$PDK_ROOT/sky130A" ] && export SKY130A_DIR="$PDK_ROOT/sky130A"\n'
  fi
  echo
  echo "# --- Graph-dataset stage (def-graph run_graphs.sh) -----------------------"
  emit_export R2G_GRAPH_PYTHON "${graph_python:-}"
}

CONTENT="$(build_content)"

if [[ "$do_dry" == "1" ]]; then
  echo "# (dry-run) would write the following to: ${TARGETS[*]}" >&2
  echo "$CONTENT"
  exit 0
fi

_ts="$(date +%s)"
for dir in "${TARGETS[@]}"; do
  [[ -d "$dir" ]] || { echo "skip (no dir): $dir" >&2; continue; }
  dst="$dir/env.local.sh"
  if [[ -f "$dst" ]]; then
    cp -- "$dst" "$dst.bak-$_ts"
    echo "backed up: $dst -> $dst.bak-$_ts" >&2
  fi
  printf '%s\n' "$CONTENT" > "$dst"
  echo "wrote: $dst" >&2
done
