"""Tests for the journal_action CLI (spec §5.2 producers)."""
import json
import subprocess
import sys
from pathlib import Path

import journal_db

CLI = Path(__file__).resolve().parents[1] / "knowledge" / "journal_action.py"


def _run(args, env_extra=None):
    import os
    env = dict(os.environ)
    env.update(env_extra or {})
    return subprocess.run([sys.executable, str(CLI)] + args,
                          capture_output=True, text=True, env=env)


def test_action_subcommand_appends_row(tmp_path):
    db = tmp_path / "journal.sqlite"
    r = _run(["action", "--project", "/p/x", "--actor", "agent",
              "--type", "config_knob_delta",
              "--payload", json.dumps({"knob": "CORE_UTILIZATION",
                                       "old": "30", "new": "20"}),
              "--db", str(db)])
    assert r.returncode == 0, r.stderr
    c = journal_db.connect(db)
    row = c.execute("SELECT actor, action_type, payload_json FROM actions").fetchone()
    assert row[0] == "agent" and row[1] == "config_knob_delta"
    assert json.loads(row[2])["knob"] == "CORE_UTILIZATION"


def test_summarize_subcommand_digests_log_file(tmp_path):
    db = tmp_path / "journal.sqlite"
    log = tmp_path / "route.log"
    log.write_text("[ERROR DRT-0085] cannot fix violation\nSignal 11 received\n")
    r = _run(["summarize", "--project", "/p/x", "--stage", "route",
              "--tool", "openroad", "--log", str(log), "--status", "fail",
              "--db", str(db)])
    assert r.returncode == 0, r.stderr
    c = journal_db.connect(db)
    assert c.execute("SELECT COUNT(*) FROM log_summaries").fetchone()[0] == 1
    # Failure log with a SIGSEGV pattern also lands a tool_bugs row.
    assert c.execute("SELECT COUNT(*) FROM tool_bugs").fetchone()[0] == 1


def test_report_subcommand_digests_json_report(tmp_path):
    """Spec rev 3: reports generated by ORFS/EDA tools are summarized too."""
    db = tmp_path / "journal.sqlite"
    rep = tmp_path / "drc.json"
    rep.write_text(json.dumps({"status": "fail", "total_violations": 7,
                               "categories": {"M3_ANTENNA": {"count": 7}}}))
    r = _run(["report", "--project", "/p/x", "--kind", "drc",
              "--file", str(rep), "--db", str(db)])
    assert r.returncode == 0, r.stderr
    c = journal_db.connect(db)
    row = c.execute("SELECT stage, status, metrics_json FROM log_summaries").fetchone()
    assert row[0] == "drc" and row[1] == "fail"
    assert json.loads(row[2])["total_violations"] == 7


def test_journal_disabled_is_silent_noop(tmp_path):
    db = tmp_path / "journal.sqlite"
    r = _run(["action", "--project", "/p/x", "--actor", "loop",
              "--type", "promote", "--db", str(db)],
             env_extra={"R2G_JOURNAL": "0"})
    assert r.returncode == 0
    assert not db.exists()


def test_bad_db_path_warns_but_exits_zero(tmp_path):
    # Journal failures must NEVER break the flow (spec §7).
    r = _run(["action", "--project", "/p/x", "--actor", "loop",
              "--type", "promote", "--db", "/nonexistent/dir/x/j.sqlite"])
    assert r.returncode == 0
    assert "WARNING" in r.stderr
