#!/usr/bin/env bash
set -euo pipefail

# usage: run_rcx.sh <project-dir> [platform] [flow_variant]
# Runs OpenRCX parasitic extraction on a completed ORFS backend run.
# Produces SPEF (Standard Parasitic Exchange Format) output.
# Results are collected into <project-dir>/rcx/

PROJECT_DIR="${1:-}"
PLATFORM="${2:-nangate45}"
# Derive FLOW_VARIANT from project directory basename (matching run_orfs.sh logic)
if [[ -n "${3:-}" ]]; then
  FLOW_VARIANT="$3"
elif [[ -n "$PROJECT_DIR" && -d "$PROJECT_DIR" ]]; then
  FLOW_VARIANT="$(basename "$(cd "$PROJECT_DIR" && pwd)")"
else
  FLOW_VARIANT="base"
fi
# Auto-detect ORFS + tools (honors ORFS_ROOT / *_EXE env overrides)
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/_env.sh"

if [[ -z "${ORFS_ROOT:-}" || ! -d "$FLOW_DIR" ]]; then
  echo "ERROR: ORFS not found. Set ORFS_ROOT to your OpenROAD-flow-scripts checkout." >&2
  exit 1
fi

if [[ -z "$PROJECT_DIR" ]]; then
  echo "usage: run_rcx.sh <project-dir> [platform]" >&2
  exit 1
fi

PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
CONFIG_MK="$PROJECT_DIR/constraints/config.mk"

if [[ ! -f "$CONFIG_MK" ]]; then
  echo "ERROR: config.mk not found at $CONFIG_MK" >&2
  exit 1
fi

DESIGN_NAME=$(grep 'DESIGN_NAME' "$CONFIG_MK" | head -1 | sed 's/.*=\s*//' | tr -d ' ')

# Check for RCX rules
PLATFORM_DIR="$FLOW_DIR/platforms/$PLATFORM"
RCX_RULES=""
for candidate in \
  "$PLATFORM_DIR/rcx_patterns.rules" \
  "$PLATFORM_DIR/openROAD/rcx/"*.rules; do
  if [[ -f "$candidate" ]]; then
    RCX_RULES="$candidate"
    break
  fi
done

if [[ -z "$RCX_RULES" ]]; then
  echo "WARNING: No RCX rules found for platform $PLATFORM" >&2
  RCX_DIR="$PROJECT_DIR/rcx"
  mkdir -p "$RCX_DIR"
  echo '{"status": "skipped", "reason": "No RCX rules available for platform '"$PLATFORM"'"}' > "$RCX_DIR/rcx_result.json"
  echo "RCX skipped: no rules for $PLATFORM"
  echo "Results: $RCX_DIR"
  exit 0
fi

# Verify ODB exists from a prior ORFS run
RESULTS_DIR="$FLOW_DIR/results/$PLATFORM/$DESIGN_NAME/$FLOW_VARIANT"
if [[ ! -d "$RESULTS_DIR" ]]; then
  RESULTS_DIR="$FLOW_DIR/results/$PLATFORM/$DESIGN_NAME"
fi

ODB_FILE=$(find "$RESULTS_DIR" -name "6_final.odb" 2>/dev/null | head -1)
if [[ -z "$ODB_FILE" ]]; then
  echo "ERROR: No 6_final.odb found in $RESULTS_DIR" >&2
  echo "Run the ORFS backend first: run_orfs.sh <project-dir>" >&2
  exit 1
fi

# Check if SPEF was already generated by the ORFS flow
SPEF_FILE="$RESULTS_DIR/6_final.spef"
if [[ -f "$SPEF_FILE" ]]; then
  echo "SPEF already generated by ORFS flow: $SPEF_FILE"
  RCX_DIR="$PROJECT_DIR/rcx"
  mkdir -p "$RCX_DIR"
  cp "$SPEF_FILE" "$RCX_DIR/" 2>/dev/null || true
  echo "Copied existing SPEF to $RCX_DIR"
  echo "Results: $RCX_DIR"
  # Still run extraction below for fresh results
fi

echo "Running OpenRCX parasitic extraction for design: $DESIGN_NAME"
echo "Platform: $PLATFORM"
echo "ODB: $ODB_FILE"
echo "RCX rules: $RCX_RULES"

# Create Tcl script for OpenRCX extraction
RCX_DIR="$PROJECT_DIR/rcx"
mkdir -p "$RCX_DIR"
SPEF_OUT="$RCX_DIR/6_final.spef"

cat > "$RCX_DIR/run_rcx.tcl" <<TCLEOF
# OpenRCX parasitic extraction script
read_db "$ODB_FILE"

# Define process corner for extraction
define_process_corner -ext_model_index 0 X

# Run parasitic extraction
extract_parasitics -ext_model_file "$RCX_RULES"

# Write SPEF output
write_spef "$SPEF_OUT"

puts "RCX extraction complete: $SPEF_OUT"
TCLEOF

# Run OpenROAD with the extraction script
RCX_TIMEOUT="${RCX_TIMEOUT:-3600}"
echo "Timeout: ${RCX_TIMEOUT}s"

# Capture exit code correctly: disable set -e and pipefail around PIPESTATUS capture
RCX_STATUS=0
set +e +o pipefail
timeout --signal=TERM --kill-after=60 "$RCX_TIMEOUT" \
  openroad -no_splash -exit "$RCX_DIR/run_rcx.tcl" 2>&1 | tee "$RCX_DIR/rcx.log"
RCX_STATUS=${PIPESTATUS[0]}
set -e -o pipefail
if [[ $RCX_STATUS -eq 124 ]]; then
  echo "ERROR: RCX timed out after ${RCX_TIMEOUT}s" >&2
fi

# Clean up temporary files
rm -f "$DESIGN_NAME.totCap" 2>/dev/null || true

# Also copy to latest backend run
BACKEND_DIR="$PROJECT_DIR/backend"
if [[ -d "$BACKEND_DIR" ]]; then
  LATEST_RUN=$(ls -d "$BACKEND_DIR"/RUN_* 2>/dev/null | sort | tail -1)
  if [[ -n "$LATEST_RUN" ]]; then
    mkdir -p "$LATEST_RUN/rcx"
    cp "$RCX_DIR"/*.spef "$LATEST_RUN/rcx/" 2>/dev/null || true
    cp "$RCX_DIR"/rcx.log "$LATEST_RUN/rcx/" 2>/dev/null || true
  fi
fi

# Report results
if [[ -f "$SPEF_OUT" ]]; then
  SPEF_SIZE=$(wc -c < "$SPEF_OUT")
  NET_COUNT=$(grep -c "^\*D_NET\|^\*R_NET" "$SPEF_OUT" 2>/dev/null || echo "0")
  echo ""
  echo "RCX extraction completed successfully"
  echo "SPEF file: $SPEF_OUT ($SPEF_SIZE bytes)"
  echo "Nets extracted: $NET_COUNT"
else
  echo ""
  echo "RCX extraction FAILED — no SPEF output generated"
  echo "Check log: $RCX_DIR/rcx.log"
fi

echo "Results: $RCX_DIR"
exit $RCX_STATUS
