#!/usr/bin/env bash
set -euo pipefail

# usage: run_rcx.sh <project-dir> [platform] [flow_variant]
# Runs OpenRCX parasitic extraction on a completed ORFS backend run.
# Produces SPEF (Standard Parasitic Exchange Format) output.
# Results are collected into <project-dir>/rcx/

PROJECT_DIR="${1:-}"
PLATFORM="${2:-sky130hd}"
# Derive FLOW_VARIANT from project directory basename (matching run_orfs.sh logic)
if [[ -n "${3:-}" ]]; then
  FLOW_VARIANT="$3"
elif [[ -n "$PROJECT_DIR" && -d "$PROJECT_DIR" ]]; then
  FLOW_VARIANT="$(basename "$(cd "$PROJECT_DIR" && pwd)")"
else
  FLOW_VARIANT="base"
fi
# Auto-detect ORFS + tools (honors ORFS_ROOT / *_EXE env overrides)
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/_env.sh"
# Bounded process-group checker supervisor (same frozen-checker contract as DRC/LVS).
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/_bounded_run.sh"
trap 'r2g_bounded_cleanup' EXIT
trap 'r2g_bounded_cleanup; exit 130' INT
trap 'r2g_bounded_cleanup; exit 143' TERM

if [[ -z "${ORFS_ROOT:-}" || ! -d "$FLOW_DIR" ]]; then
  echo "ERROR: ORFS not found. Set ORFS_ROOT to your OpenROAD-flow-scripts checkout." >&2
  exit 1
fi

if [[ -z "$PROJECT_DIR" ]]; then
  echo "usage: run_rcx.sh <project-dir> [platform]" >&2
  exit 1
fi

PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
KNOWLEDGE_DIR_J="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../knowledge" && pwd)"
CONFIG_MK="$PROJECT_DIR/constraints/config.mk"

if [[ ! -f "$CONFIG_MK" ]]; then
  echo "ERROR: config.mk not found at $CONFIG_MK" >&2
  exit 1
fi

DESIGN_NAME=$(grep -E '^[[:space:]]*export[[:space:]]+DESIGN_NAME[[:space:]]*=' "$CONFIG_MK" | head -1 | sed 's/.*=\s*//' | tr -d ' ')
DESIGN_NICKNAME=$(grep -E '^[[:space:]]*export[[:space:]]+DESIGN_NICKNAME[[:space:]]*=' "$CONFIG_MK" | head -1 | sed 's/.*=\s*//' | tr -d ' ' || true)
DESIGN_NICKNAME="${DESIGN_NICKNAME:-$DESIGN_NAME}"

# Check for RCX rules
PLATFORM_DIR="$FLOW_DIR/platforms/$PLATFORM"
RCX_RULES=""
for candidate in \
  "$PLATFORM_DIR/rcx_patterns.rules" \
  "$PLATFORM_DIR/openROAD/rcx/"*.rules; do
  if [[ -f "$candidate" ]]; then
    RCX_RULES="$candidate"
    break
  fi
done

if [[ -z "$RCX_RULES" ]]; then
  echo "WARNING: No RCX rules found for platform $PLATFORM" >&2
  RCX_DIR="$PROJECT_DIR/rcx"
  mkdir -p "$RCX_DIR"
  echo '{"status": "skipped", "reason": "No RCX rules available for platform '"$PLATFORM"'"}' > "$RCX_DIR/rcx_result.json"
  echo "RCX skipped: no rules for $PLATFORM"
  echo "Results: $RCX_DIR"
  exit 0
fi

# Re-stage the exact preserved backend run before extraction, using the same
# identity resolver/provenance record as DRC and LVS.
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/_restage_for_signoff.sh"
RESULTS_DIR="$ORFS_RESULTS_DIR"

ODB_FILE=$(find "$RESULTS_DIR" -name "6_final.odb" 2>/dev/null | head -1)
if [[ -z "$ODB_FILE" ]]; then
  echo "ERROR: No 6_final.odb found in $RESULTS_DIR" >&2
  echo "Run the ORFS backend first: run_orfs.sh <project-dir>" >&2
  exit 1
fi

# Check if SPEF was already generated by the ORFS flow
SPEF_FILE="$RESULTS_DIR/6_final.spef"
if [[ -f "$SPEF_FILE" ]]; then
  echo "SPEF already generated by ORFS flow: $SPEF_FILE"
  RCX_DIR="$PROJECT_DIR/rcx"
  mkdir -p "$RCX_DIR"
  cp "$SPEF_FILE" "$RCX_DIR/orfs_6_final.spef" 2>/dev/null || true
  echo "Preserved existing ORFS SPEF as independent input evidence"
  echo "Results: $RCX_DIR"
  # Still run extraction below for fresh results
fi

echo "Running OpenRCX parasitic extraction for design: $DESIGN_NAME"
echo "Platform: $PLATFORM"
echo "ODB: $ODB_FILE"
echo "RCX rules: $RCX_RULES"

# Create Tcl script for OpenRCX extraction
RCX_DIR="$PROJECT_DIR/rcx"
mkdir -p "$RCX_DIR"
SPEF_OUT="$RCX_DIR/6_final.spef"
# A failed fresh extraction must never inherit a stale successful SPEF/result.
rm -f "$SPEF_OUT" "$RCX_DIR/rcx_result.json" "$RCX_DIR/rcx_provenance.json"
ODB_SHA_PRE="$(sha256sum "$ODB_FILE" 2>/dev/null | cut -d' ' -f1 || true)"
RULES_SHA="$(sha256sum "$RCX_RULES" 2>/dev/null | cut -d' ' -f1 || true)"
RCX_STARTED_AT="$(date -Iseconds)"

cat > "$RCX_DIR/run_rcx.tcl" <<TCLEOF
# OpenRCX parasitic extraction script
read_db "$ODB_FILE"

# Define process corner for extraction
define_process_corner -ext_model_index 0 X

# Run parasitic extraction
extract_parasitics -ext_model_file "$RCX_RULES"

# Write SPEF output
write_spef "$SPEF_OUT"

puts "RCX extraction complete: $SPEF_OUT"
TCLEOF

# Run OpenROAD with the extraction script
RCX_TIMEOUT="${RCX_TIMEOUT:-3600}"
echo "Timeout: ${RCX_TIMEOUT}s"

# Capture exit code correctly and reap every OpenROAD descendant on timeout.
RCX_STATUS=0
set +e
cd "$RCX_DIR"
r2g_bounded_run "$RCX_TIMEOUT" "${RCX_KILL_GRACE:-60}" "$RCX_DIR/rcx.log" \
  "${OPENROAD_EXE:-openroad}" -no_splash -exit "$RCX_DIR/run_rcx.tcl"
RCX_STATUS=$?
set -e
tail -n 25 "$RCX_DIR/rcx.log" 2>/dev/null || true
rm -f "$RCX_DIR/$DESIGN_NAME.totCap" 2>/dev/null || true
if [[ $RCX_STATUS -eq 124 ]]; then
  echo "ERROR: RCX timed out after ${RCX_TIMEOUT}s" >&2
fi

# Frozen-layout postcondition: RCX may create only the run-local SPEF; it must
# not mutate the ODB it grades.
ODB_SHA_POST="$(sha256sum "$ODB_FILE" 2>/dev/null | cut -d' ' -f1 || true)"
if [[ -z "$ODB_SHA_PRE" || "$ODB_SHA_PRE" != "$ODB_SHA_POST" ]]; then
  echo "ERROR: RCX changed or lost the frozen ODB" >&2
  RCX_STATUS=1
fi

# Copy to the SELECTED backend run (RMD-P0-02: the shared resolver's pick,
# never `ls | tail -1` — a newer empty RUN dir must not adopt this SPEF).
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/_backend_run.sh"
TARGET_RUN="${R2G_BACKEND_RUN:-$(r2g_pick_backend_run "$PROJECT_DIR" || true)}"
if [[ -z "$TARGET_RUN" || ! -d "$TARGET_RUN" ]]; then
  TARGET_RUN=$(ls -d "$PROJECT_DIR/backend"/RUN_* 2>/dev/null | sort | tail -1 || true)
fi
RCX_RUN_TAG=""
[[ -n "$TARGET_RUN" ]] && RCX_RUN_TAG="$(basename "$TARGET_RUN")"
# Report results
if [[ $RCX_STATUS -eq 0 && -s "$SPEF_OUT" ]]; then
  SPEF_SIZE=$(wc -c < "$SPEF_OUT")
  NET_COUNT=$(awk '/^\*D_NET|^\*R_NET/{n++} END{print n+0}' "$SPEF_OUT")
  SPEF_SHA="$(sha256sum "$SPEF_OUT" | cut -d' ' -f1)"
  printf '{"status":"complete","checker":"openrcx","nets":%s,"spef_bytes":%s,"odb_sha256":"%s","spef_sha256":"%s","run_tag":"%s"}\n' \
    "$NET_COUNT" "$SPEF_SIZE" "$ODB_SHA_PRE" "$SPEF_SHA" "$RCX_RUN_TAG" \
    > "$RCX_DIR/rcx_result.json"
  echo ""
  echo "RCX extraction completed successfully"
  echo "SPEF file: $SPEF_OUT ($SPEF_SIZE bytes)"
  echo "Nets extracted: $NET_COUNT"
else
  [[ $RCX_STATUS -ne 0 ]] || RCX_STATUS=1
  printf '{"status":"failed","reason":"fresh_extraction_failed","returncode":%s,"odb_sha256":"%s","run_tag":"%s"}\n' \
    "$RCX_STATUS" "$ODB_SHA_PRE" "$RCX_RUN_TAG" \
    > "$RCX_DIR/rcx_result.json"
  echo ""
  echo "RCX extraction FAILED — no SPEF output generated"
  echo "Check log: $RCX_DIR/rcx.log"
fi

python3 - "$RCX_DIR/rcx_provenance.json" "$ODB_FILE" "$ODB_SHA_PRE" \
  "$RCX_RULES" "$RULES_SHA" "$SPEF_OUT" "$RCX_STARTED_AT" "${TARGET_RUN:-}" <<'PYEOF'
import json, os, sys, time
out, odb, odb_sha, rules, rules_sha, spef, started, run_dir = sys.argv[1:9]
doc = {"engine": "openrcx", "run_tag": os.path.basename(run_dir) if run_dir else None,
       "odb_path": odb, "odb_sha256": odb_sha or None,
       "rules_path": rules, "rules_sha256": rules_sha or None,
       "spef_path": spef, "started_at": started,
       "ended_at": time.strftime("%Y-%m-%dT%H:%M:%S%z")}
with open(out, "w") as f:
    json.dump(doc, f, indent=2); f.write("\n")
PYEOF

if [[ -n "$TARGET_RUN" && -d "$TARGET_RUN" ]]; then
  mkdir -p "$TARGET_RUN/rcx"
  cp "$RCX_DIR"/6_final.spef "$TARGET_RUN/rcx/" 2>/dev/null || true
  cp "$RCX_DIR"/rcx.log "$RCX_DIR"/rcx_result.json \
     "$RCX_DIR"/rcx_provenance.json "$TARGET_RUN/rcx/" 2>/dev/null || true
fi

echo "Results: $RCX_DIR"

# Tier-0 journal: digest this check's tool log + extracted report (never breaks the flow).
[[ -f "$RCX_DIR/rcx.log" ]] && python3 "$KNOWLEDGE_DIR_J/journal_db.py" summarize \
  --project "$PROJECT_DIR" --stage rcx --tool openrcx --log "$RCX_DIR/rcx.log" \
  ${R2G_JOURNAL_DB:+--db "$R2G_JOURNAL_DB"} 2>/dev/null || true
[[ -f "$PROJECT_DIR/reports/rcx.json" ]] && python3 "$KNOWLEDGE_DIR_J/journal_db.py" report \
  --project "$PROJECT_DIR" --kind rcx --file "$PROJECT_DIR/reports/rcx.json" \
  ${R2G_JOURNAL_DB:+--db "$R2G_JOURNAL_DB"} 2>/dev/null || true

exit $RCX_STATUS
